// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy5go0ri5hj7bRNViWu2J_zE_owzXA2eU',
    appId: '1:529362657289:web:186d5ab3d285cf868b98d8',
    messagingSenderId: '529362657289',
    projectId: 'tp3-mobile-avance',
    authDomain: 'tp3-mobile-avance.firebaseapp.com',
    storageBucket: 'tp3-mobile-avance.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX8-ju-fuj9-9H_W196oZh28rr4zAr0Cc',
    appId: '1:529362657289:android:31d668f21e92ba4c8b98d8',
    messagingSenderId: '529362657289',
    projectId: 'tp3-mobile-avance',
    storageBucket: 'tp3-mobile-avance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpLrZPBvwh_krl4wbnbTywN4DVH30CGhs',
    appId: '1:529362657289:ios:12126c4e7abc96358b98d8',
    messagingSenderId: '529362657289',
    projectId: 'tp3-mobile-avance',
    storageBucket: 'tp3-mobile-avance.appspot.com',
    iosClientId: '529362657289-0m83ernf4ba1v879n0j9i3d5t2p28csr.apps.googleusercontent.com',
    iosBundleId: 'com.deadinside.tp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpLrZPBvwh_krl4wbnbTywN4DVH30CGhs',
    appId: '1:529362657289:ios:12126c4e7abc96358b98d8',
    messagingSenderId: '529362657289',
    projectId: 'tp3-mobile-avance',
    storageBucket: 'tp3-mobile-avance.appspot.com',
    iosClientId: '529362657289-0m83ernf4ba1v879n0j9i3d5t2p28csr.apps.googleusercontent.com',
    iosBundleId: 'com.deadinside.tp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy5go0ri5hj7bRNViWu2J_zE_owzXA2eU',
    appId: '1:529362657289:web:3d571bcea3cd52ca8b98d8',
    messagingSenderId: '529362657289',
    projectId: 'tp3-mobile-avance',
    authDomain: 'tp3-mobile-avance.firebaseapp.com',
    storageBucket: 'tp3-mobile-avance.appspot.com',
  );

}